"""
Fusion Engine — Multimodal fusion orchestrator.

Combines outputs from Audio, NLP, and Vision modules into a unified
behavioral risk assessment with explainability.

Architecture:
    FusionEngine (this file)
    ├── RiskScorer          — Weighted domain scoring + crisis override
    └── ContradictionDetector — Cross-modal mismatch detection

Pipeline:
    Audio Features ─┐
                    ├──► RiskScorer ──────────► Risk Band + Score
    NLP Features ───┤
                    ├──► ContradictionDetector ► Mismatch Flags
    Vision Features ┘
                    └──► Confidence + Escalation ► Recommendations
                                │
                                ▼
                        Final JSON Report

IMPORTANT ETHICAL CONSTRAINT:
    This system is a DECISION-SUPPORT TOOL ONLY.
    It does NOT produce psychiatric diagnoses.
    All outputs are framed as "behavioral concern indicators"
    to support — NOT replace — clinical judgment.

Output Schema:
    {
        "risk_assessment": {
            "risk_band": str,           # "Low Concern" | "Moderate Concern" | "High Concern"
            "risk_score": float,        # 0.0 - 1.0
            "sub_scores": {...},
            "flags": [...],
            "contributors": [str],
            "crisis_override": bool
        },
        "confidence": {
            "score": float,             # 0.0 - 1.0
            "modalities_available": [str],
            "modalities_missing": [str],
            "quality_notes": [str]
        },
        "contradictions": {
            "contradictions": [...],
            "contradiction_count": int,
            "overall_incongruence_score": float
        },
        "escalation": {
            "recommended": bool,
            "urgency": str,             # "ROUTINE" | "PRIORITY" | "URGENT"
            "reasons": [str]
        },
        "explainability": {
            "summary": str,             # Human-readable assessment summary
            "modality_contributions": {...},
            "decision_factors": [str],
            "disclaimer": str
        }
    }
"""
import logging
from typing import Dict, Optional

logger = logging.getLogger(__name__)

# Disclaimer appended to every report
DISCLAIMER = (
    "This analysis is generated by an AI decision-support system and is intended "
    "to assist clinical evaluation. It does NOT constitute a psychiatric diagnosis. "
    "All findings must be reviewed and interpreted by a qualified mental health "
    "professional in the context of a comprehensive clinical assessment."
)


class FusionEngine:
    """
    Fuses multimodal analysis outputs into a unified behavioral
    risk assessment.

    This is the final stage of the analysis pipeline:
        Audio → NLP → Vision → **Fusion**

    Usage:
        engine = FusionEngine()
        report = engine.fuse(
            audio=audio_result,
            nlp=nlp_result,
            vision=vision_result,
        )
    """

    def __init__(self, risk_weights: Optional[Dict] = None):
        """
        Args:
            risk_weights: Optional custom weights for risk domains.
                          Keys: "psychomotor", "cognitive", "affective", "behavioral"
                          Must sum to 1.0.
        """
        from app.modules.fusion.risk_scorer import RiskScorer
        from app.modules.fusion.contradiction import ContradictionDetector

        self.risk_scorer = RiskScorer(weights=risk_weights)
        self.contradiction_detector = ContradictionDetector()

    def fuse(
        self,
        audio: Dict = None,
        nlp: Dict = None,
        vision: Dict = None,
    ) -> Dict:
        """
        Fuse multimodal features into a comprehensive behavioral report.

        Args:
            audio: Output from AudioProcessor (transcript + prosody + speech_features)
            nlp: Output from NLPProcessor (sentiment + lexical + meta)
            vision: Output from VisionProcessor (aggregate + stability + per_second)

        All arguments are optional — the system degrades gracefully
        with fewer modalities (reflected in confidence score).

        Returns:
            Unified report with risk assessment, confidence, contradictions,
            escalation recommendation, and explainability.
        """
        audio = audio or {}
        nlp = nlp or {}
        vision = vision or {}

        # ── Step 1: Risk Assessment ──────────────────
        risk_assessment = self.risk_scorer.calculate(audio, nlp, vision)

        # ── Step 2: Confidence Scoring ───────────────
        confidence = self._calculate_confidence(audio, nlp, vision)

        # ── Step 3: Contradiction Detection ──────────
        contradictions = self.contradiction_detector.detect(audio, nlp, vision)

        # ── Step 4: Escalation Recommendation ────────
        escalation = self._determine_escalation(risk_assessment, contradictions)

        # ── Step 5: Explainability ───────────────────
        explainability = self._generate_explainability(
            risk_assessment, confidence, contradictions, escalation
        )

        return {
            "risk_assessment": risk_assessment,
            "confidence": confidence,
            "contradictions": contradictions,
            "escalation": escalation,
            "explainability": explainability,
        }

    # ── Confidence Scoring ───────────────────────────

    @staticmethod
    def _calculate_confidence(audio: Dict, nlp: Dict, vision: Dict) -> Dict:
        """
        Calculate confidence in the assessment based on data quality.

        Confidence factors:
            - Number of modalities available (0-3)
            - Data quality within each modality
            - Session duration (very short = less reliable)
        """
        available = []
        missing = []
        quality_notes = []
        quality_scores = []

        # Audio availability and quality
        audio_status = audio.get("status", "error")
        if audio_status in ("success", "partial"):
            available.append("Audio")
            # Quality based on transcription
            seg_count = audio.get("transcript", {}).get("segment_count", 0)
            if seg_count > 5:
                quality_scores.append(1.0)
            elif seg_count > 0:
                quality_scores.append(0.6)
                quality_notes.append(f"Limited audio segments ({seg_count})")
            else:
                quality_scores.append(0.3)
                quality_notes.append("Audio available but no speech segments detected")
        else:
            missing.append("Audio")

        # NLP availability and quality
        nlp_status = nlp.get("status", "error")
        if nlp_status in ("success", "partial"):
            available.append("NLP")
            word_count = nlp.get("meta", {}).get("total_words", 0)
            if word_count > 50:
                quality_scores.append(1.0)
            elif word_count > 10:
                quality_scores.append(0.6)
                quality_notes.append(f"Limited text ({word_count} words)")
            else:
                quality_scores.append(0.3)
                quality_notes.append("Very short transcript — NLP results less reliable")
        else:
            missing.append("NLP")

        # Vision availability and quality
        vision_status = vision.get("status", "error")
        if vision_status in ("success", "partial"):
            available.append("Vision")
            detection_rate = vision.get("face_detection_rate", 0)
            if detection_rate > 0.7:
                quality_scores.append(1.0)
            elif detection_rate > 0.3:
                quality_scores.append(0.6)
                quality_notes.append(f"Face detected in {detection_rate:.0%} of frames")
            else:
                quality_scores.append(0.3)
                quality_notes.append("Low face detection rate — vision results unreliable")
        else:
            missing.append("Vision")

        # Overall confidence
        modality_factor = len(available) / 3.0
        quality_factor = float(sum(quality_scores) / max(len(quality_scores), 1))
        confidence_score = modality_factor * 0.5 + quality_factor * 0.5

        if not available:
            quality_notes.append("No modalities available — assessment not possible")
            confidence_score = 0.0

        return {
            "score": round(confidence_score, 3),
            "modalities_available": available,
            "modalities_missing": missing,
            "quality_notes": quality_notes,
        }

    # ── Escalation Recommendation ────────────────────

    @staticmethod
    def _determine_escalation(risk: Dict, contradictions: Dict) -> Dict:
        """
        Determine if the session warrants escalated clinical attention.

        Escalation Levels:
            ROUTINE   — No immediate action required
            PRIORITY  — Should be reviewed before next scheduled session
            URGENT    — Requires immediate clinical attention

        Triggers:
            URGENT: Crisis language OR risk_score > 0.8
            PRIORITY: Risk band "High Concern" OR high contradictions
            ROUTINE: Everything else
        """
        reasons = []
        risk_score = risk.get("raw_score", 0)
        risk_band = risk.get("risk_band", "Low Concern")
        crisis = risk.get("crisis_override", False)
        contradiction_count = contradictions.get("contradiction_count", 0)
        highest_severity = contradictions.get("highest_severity", "NONE")

        # URGENT triggers
        if crisis:
            reasons.append("Crisis language detected — immediate safety review required")
            return {"recommended": True, "urgency": "URGENT", "reasons": reasons}

        if risk_score > 0.80:
            reasons.append(f"Very high risk score ({risk_score:.2f}) — immediate review recommended")
            return {"recommended": True, "urgency": "URGENT", "reasons": reasons}

        # PRIORITY triggers
        if risk_band == "High Concern":
            reasons.append(f"High Concern risk band (score: {risk_score:.2f})")

        if highest_severity == "HIGH":
            reasons.append(f"{contradiction_count} cross-modal contradictions detected (HIGH severity)")

        if risk_score > 0.60:
            reasons.append(f"Elevated risk score ({risk_score:.2f})")

        if reasons:
            return {"recommended": True, "urgency": "PRIORITY", "reasons": reasons}

        # ROUTINE
        if risk_band == "Moderate Concern":
            reasons.append("Moderate behavioral indicators — monitor at next session")
        else:
            reasons.append("No significant behavioral concerns identified")

        return {"recommended": False, "urgency": "ROUTINE", "reasons": reasons}

    # ── Explainability ───────────────────────────────

    @staticmethod
    def _generate_explainability(
        risk: Dict, confidence: Dict, contradictions: Dict, escalation: Dict
    ) -> Dict:
        """
        Generate human-readable explanation of the assessment.

        Provides:
            - Natural language summary
            - Per-modality contribution breakdown
            - Key decision factors
            - Ethical disclaimer
        """
        sub_scores = risk.get("sub_scores", {})
        risk_band = risk.get("risk_band", "Low Concern")
        risk_score = risk.get("raw_score", 0)
        confidence_score = confidence.get("score", 0)
        modalities = confidence.get("modalities_available", [])
        contradiction_count = contradictions.get("contradiction_count", 0)

        # ── Natural Language Summary ─────────────────
        summary_parts = [
            f"Assessment based on {len(modalities)} modality/modalities "
            f"({', '.join(modalities) or 'none'}) "
            f"with {confidence_score:.0%} confidence."
        ]

        if risk_band == "High Concern":
            summary_parts.append(
                f"Multiple behavioral indicators suggest elevated concern "
                f"(score: {risk_score:.2f}). Clinical review is recommended."
            )
        elif risk_band == "Moderate Concern":
            summary_parts.append(
                f"Some behavioral indicators are present (score: {risk_score:.2f}). "
                f"Continued monitoring is suggested."
            )
        else:
            summary_parts.append(
                f"No significant behavioral concerns detected (score: {risk_score:.2f})."
            )

        if contradiction_count > 0:
            summary_parts.append(
                f"{contradiction_count} cross-modal contradiction(s) detected, "
                f"which may indicate incongruent affect."
            )

        if risk.get("crisis_override", False):
            summary_parts.insert(1,
                "⚠️ SAFETY ALERT: Crisis-related language was detected. "
                "Immediate clinical review is strongly recommended."
            )

        summary = " ".join(summary_parts)

        # ── Modality Contributions ───────────────────
        contributions = {}
        total = sum(sub_scores.values()) or 1
        for domain, score in sub_scores.items():
            contributions[domain] = {
                "score": score,
                "contribution_pct": round(score / total * 100, 1),
            }

        # ── Decision Factors ─────────────────────────
        # Collect the most impactful factors
        decision_factors = risk.get("contributors", [])
        if contradiction_count > 0:
            decision_factors.append(
                f"{contradiction_count} cross-modal contradiction(s) flagged"
            )

        return {
            "summary": summary,
            "modality_contributions": contributions,
            "decision_factors": decision_factors,
            "disclaimer": DISCLAIMER,
        }
